### ISSUE TITLE
Lost transitive dependencies during mavenCentral migration

### ISSUE THREAD

**Issue by TWiStErRob** [linkedin/test-butler#121]
While upgrading from 2.1.1 to 2.2.1 we noticed that some dependencies disappeared from `gradlew :app:dependencies`.
Specifically junit + test-butler-api, and I can confirm this by noticing that they went from compile to runtime here:
https://mvnrepository.com/artifact/com.linkedin.testbutler/test-butler-library/2.1.1
<img width=50% src=https://user-images.githubusercontent.com/2906988/182121033-af6a909b-c089-42c6-aee8-eb02b004ea73.png />

https://mvnrepository.com/artifact/com.linkedin.testbutler/test-butler-library/2.2.1
<img width=50% src=https://user-images.githubusercontent.com/2906988/182121075-24336418-0165-450a-9e38-a9b50cf34789.png />

Was this an intentional change?

**Comment by TWiStErRob** [comment]
Note: they still exist on `debugAndroidTestRuntimeClasspath - Runtime classpath of compilation 'googleDebugAndroidTest' (target  (androidJvm)).`, so I think most users are fine, unless they accessed code from `-api` which is essentially `com.linkedin.android.testbutler.ButlerApi.Stub.Proxy`. I think users will be fine, but maybe worth noting in changelog?

**Comment by drewhannay** [comment]
Good catch. It may not have been intentional, but I think it's correct. Really I think the bug is we didn't realize junit was leaking to the compile classpath before this change 😄 

We were already declaring junit as an `implementation` dependency, but I think our old publishing setup was incorrect and declaring it as an `api` dependency in the published artifact files. Now it's being correctly published as `implementation` (aka runtime) which explains what you're seeing.

**Comment by drewhannay** [comment]
Done!

**Comment by TWiStErRob** [comment]
Cheers! Thanks for the quick turnaround!
